name: 欢迎来到我的空间
author: 小李子
url: http://localhost:4000/
baseurl: 
resume_site: 
description: 
github_username: 
github: 
plugins: [jekyll-paginate]
permalink: /:year-:month-:day-:title
paginate: 12
paginate_path: "/page/:num/"
exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']
highlighter: rouge
markdown: kramdown
comments :
  gitalk :
    clientID : e30010a6e2c315019783
    clientSecret : 27341db7e9b7da2c63f83d7da3914c4c9ae2a3ae
    repo : comments
    owner : Lee-Sep
    admin : [Lee-Sep]
